# Generated by Django 5.1.7 on 2025-03-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=128)),
                ('picture', models.TextField()),
                ('price', models.IntegerField()),
                ('info', models.TextField()),
            ],
        ),
    ]
